namespace CommercialSpaceRentalV2.Constants.Enums
{
  public enum ActionType
  {
    USER_REGISTER,
    USER_UPDATE_PROFILE,
    USER_DELETE,
    USER_LOGIN,
    USER_LOGOUT,
    USER_PASSWORD_RESET,

    BOOK_ROOM,
    CANCEL_BOOKING,
    ADMIN_CANCEL_BOOKING,
    UPDATE_BOOKING,
    CONFIRM_BOOKING,
    COMPLETE_BOOKING,

    CREATE_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    ASSIGN_SERVICE_TO_ROOM,
    REMOVE_SERVICE_FROM_ROOM,

    CREATE_LOCATION,
    UPDATE_LOCATION,
    DELETE_LOCATION,

    CREATE_SERVICE,
    UPDATE_SERVICE,
    DELETE_SERVICE,
    ENABLE_SERVICE_FOR_LOCATION,
    DISABLE_SERVICE_FOR_LOCATION,
    UNASSIGN_SERVICE_FROM_ROOM,

    SYNC_TO_ACCOUNTING,
    ACCOUNTING_SYNC_FAILED,

    ADMIN_LOGIN,
    ADMIN_LOGOUT,
    GRANT_ADMIN_ROLE,
    REVOKE_ADMIN_ROLE,

    SYSTEM_MAINTENANCE_START,
    SYSTEM_MAINTENANCE_END,

    BULK_IMPORT_ROOMS,
    EXPORT_REPORT,
    SEND_NOTIFICATION
  }
}
